In [ ]:
!pip install sweetviz
!pip install pandas
!pip install dataprofiler
!pip install ydata_profiling
!pip install pandera

Requirement already satisfied: sweetviz in c:\users\menna\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (2.2.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (1.26.4)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (3.9.3)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (4.66.5)
Requirement already satisfied: scipy>=1.3.2 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (1.13.1)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in c:\users\menna\anaconda3\lib\site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\menna\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\menna\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\menna\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2023.3)
Requirement already satisfied: colorama in c:\users\menna\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\menna\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.16.0)
Requirement already satisfied: pandas in c:\users\menna\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\menna\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\menna\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\menna\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\menna\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\menna\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: dataprofiler in c:\users\menna\anaconda3\lib\site-packages (0.13.4)
Requirement already satisfied: h5py>=2.10.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (3.11.0)
Requirement already satisfied: wheel>=0.33.1 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (0.44.0)
Requirement already satisfied: numpy<2.0.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (1.26.4)
Requirement already satisfied: pandas>=1.1.2 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (2.2.3)
Requirement already satisfied: python-dateutil>=2.7.5 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (2024.1)
Requirement already satisfied: pyarrow>=1.0.1 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (16.1.0)
Requirement already satisfied: chardet>=3.0.4 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (5.2.0)
Requirement already satisfied: fastavro>=1.1.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (1.12.1)
Requirement already satisfied: python-snappy>=0.7.1 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (0.7.3)
Requirement already satisfied: charset-normalizer>=1.3.6 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (3.3.2)
Requirement already satisfied: psutil>=4.0.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (7.0.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (1.13.1)
Requirement already satisfied: requests==2.32.* in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (2.32.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (3.3)
Requirement already satisfied: typing-extensions>=3.10.0.2 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (4.14.1)
Requirement already satisfied: HLL>=2.0.3 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (3.0.0)
Requirement already satisfied: datasketches>=4.1.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (5.2.0)
Requirement already satisfied: packaging>=23.0 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (24.1)
Requirement already satisfied: boto3>=1.28.61 in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (1.42.88)
Requirement already satisfied: versioneer in c:\users\menna\anaconda3\lib\site-packages (from dataprofiler) (0.29)
Requirement already satisfied: idna<4,>=2.5 in c:\users\menna\anaconda3\lib\site-packages (from requests==2.32.*->dataprofiler) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\menna\anaconda3\lib\site-packages (from requests==2.32.*->dataprofiler) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\menna\anaconda3\lib\site-packages (from requests==2.32.*->dataprofiler) (2025.8.3)
Requirement already satisfied: botocore<1.43.0,>=1.42.88 in c:\users\menna\anaconda3\lib\site-packages (from boto3>=1.28.61->dataprofiler) (1.42.88)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\menna\anaconda3\lib\site-packages (from boto3>=1.28.61->dataprofiler) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\menna\anaconda3\lib\site-packages (from boto3>=1.28.61->dataprofiler) (0.16.0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\menna\anaconda3\lib\site-packages (from pandas>=1.1.2->dataprofiler) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\menna\anaconda3\lib\site-packages (from python-dateutil>=2.7.5->dataprofiler) (1.16.0)
Requirement already satisfied: cramjam in c:\users\menna\anaconda3\lib\site-packages (from python-snappy>=0.7.1->dataprofiler) (2.11.0)
Requirement already satisfied: ydata_profiling in c:\users\menna\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (3.9.3)
Requirement already satisfied: pydantic<3,>=2 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\menna\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (1.26.4)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (4.66.5)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (0.14.2)
Requirement already satisfied: typeguard<5,>=4 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\menna\anaconda3\lib\site-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in c:\users\menna\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata_profiling) (1.7.0)
Requirement already satisfied: pillow in c:\users\menna\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata_profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\menna\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata_profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\menna\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\menna\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\menna\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\menna\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in c:\users\menna\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata_profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\menna\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\menna\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\menna\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\menna\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\menna\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\menna\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\menna\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\menna\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (2025.8.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\menna\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (0.5.6)
Requirement already satisfied: colorama in c:\users\menna\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata_profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\menna\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (24.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\menna\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.3)
Requirement already satisfied: puremagic in c:\users\menna\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (2.2.0)
Requirement already satisfied: six in c:\users\menna\anaconda3\lib\site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata_profiling) (1.16.0)
Requirement already satisfied: pandera in c:\users\menna\anaconda3\lib\site-packages (0.30.1)
Requirement already satisfied: packaging>=20.0 in c:\users\menna\anaconda3\lib\site-packages (from pandera) (24.1)
Requirement already satisfied: pydantic in c:\users\menna\anaconda3\lib\site-packages (from pandera) (2.11.7)
Requirement already satisfied: typeguard in c:\users\menna\anaconda3\lib\site-packages (from pandera) (4.5.1)
Requirement already satisfied: typing_extensions in c:\users\menna\anaconda3\lib\site-packages (from pandera) (4.14.1)
Requirement already satisfied: typing_inspect>=0.6.0 in c:\users\menna\anaconda3\lib\site-packages (from pandera) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\menna\anaconda3\lib\site-packages (from typing_inspect>=0.6.0->pandera) (1.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\menna\anaconda3\lib\site-packages (from pydantic->pandera) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\menna\anaconda3\lib\site-packages (from pydantic->pandera) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\menna\anaconda3\lib\site-packages (from pydantic->pandera) (0.4.1)

In [ ]:
import pandas as pd
import json
from ydata_profiling import ProfileReport
from dataprofiler import Data, Profiler
import sweetviz as sv
import pandera as pa
from pandera import Column, DataFrameSchema, Check, Index

In [ ]:
df=pd.read_csv("hotels_data.csv", encoding="latin1")

In [ ]:
df

,countyCode,countyName,cityCode,cityName,HotelCode,HotelName,HotelRating,Address,Attractions,Description,FaxNumber,HotelFacilities,Map,PhoneNumber,PinCode,HotelWebsiteUrl
0,AL,Albania,106078,Albanien,1003300,De Paris Hotel,FourStar,Nr. 7 Brigada Viii Street Tirane,NaN,Hotel de Paris is a charming boutique hotel th...,42268822,Private parking Parking onsite Television in c...,41.32213|19.81665,00355 4226 5009,1000,https://www.booking.com/hotel/al/de-paris.html
1,AL,Albania,106078,Albanien,1003301,Hotel Green,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,NaN,"Located in a suburb of Tirana, Hotel Green is ...",35548520058,airport pick up wifi available in all areas Ai...,41.30413|19.74703,+35548520057,1041,https://www.booking.com/hotel/al/hotel-green.html
2,AL,Albania,106078,Albanien,1003302,Theranda Hotel,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,NaN,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",00355 (0)42273689,face masks for guests available all plates cu...,41.3216|19.81199,00355 (0)42273766,1019,https://www.booking.com/hotel/al/theranda.html
3,AL,Albania,106078,Albanien,1003303,Seven Hotel,ThreeStar,"KAVAJA STREET, CLOSE TURKISH AMBASSY TIRANA",Skanderbeg Square: within 500 metre,This hotel enjoys an enviable setting in Tiran...,NaN,À la carte dinner Breakfast buffet Breakfast C...,41.328027|19.815052,NaN,1001,http://www.hotelseven-tirana.com/
4,AL,Albania,106078,Albanien,1003325,Viktoria,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,NaN,Located in a new residential area at the edge ...,+355695406986,internet services Ironing service Family rooms...,41.29125|19.85349,355 69 5406986,1000,https://www.booking.com/hotel/al/viktoria-sauk...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010028,ZW,Zimbabwe,141497,Victoria Falls,5909458,Eagles House,All,Aerodrome Suburbs,NaN,NaN,NaN,NaN,-17.931957|25.81875,NaN,NaN,NaN
1010029,ZW,Zimbabwe,141497,Victoria Falls,6008100,Losin Guest House,TwoStar,1271 Aerodrome Victoria Falls Town,Distances are displayed to the nearest 0.1 mil...,<p>HeadLine : In a national park</p><p>Locatio...,NaN,Barbecue grill(s) Water dispenser Breakfast av...,-18.092278|25.843654,263-783130516,00263,NaN
1010030,ZW,Zimbabwe,141497,Victoria Falls,6053177,Victoria Falls Spacious Cottage,All,Syringa Road,NaN,"Featuring garden views, Victoria Falls Holiday...",NaN,Parking Private check-in/check-out Pets allowe...,-17.92898|25.82036,NaN,NaN,https://www.booking.com/hotel/zw/victoria-fall...
1010031,ZW,Zimbabwe,141497,Victoria Falls,6092731,848 Guest House,ThreeStar,848 Aerodrome,Distances are displayed to the nearest 0.1 mil...,<p>HeadLine : In Victoria Falls</p><p>Location...,NaN,Dry cleaning/laundry service Designated smokin...,-17.929912|25.821958,263-772855945,263,NaN
1010032,ZW,Zimbabwe,141497,Victoria Falls,6105635,Mbano Manor Hotel - All Inclusive,ThreeStar,Old Kazungula Road,Distances are displayed to the nearest 0.1 mil...,<p>HeadLine : In a national park</p><p>Locatio...,NaN,Locally-owned & organized tours & activities F...,-17.92706|25.809958,27-719012911,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010033 entries, 0 to 1010032
Data columns (total 16 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   countyCode        1009121 non-null  object
 1    countyName       1010033 non-null  object
 2    cityCode         1010033 non-null  int64
 3    cityName         1010033 non-null  object
 4    HotelCode        1010033 non-null  int64
 5    HotelName        1010033 non-null  object
 6    HotelRating      1010033 non-null  object
 7    Address          1009931 non-null  object
 8    Attractions      484941 non-null   object
 9    Description      963028 non-null   object
 10   FaxNumber        449686 non-null   object
 11   HotelFacilities  959655 non-null   object
 12   Map              1009103 non-null  object
 13   PhoneNumber      682896 non-null   object
 14   PinCode          979054 non-null   object
 15   HotelWebsiteUrl  759915 non-null   object
dtypes: int64(2), object(14)
memory usage: 123.3+ MB

In [ ]:
df.isna().sum()

countyCode             912
 countyName              0
 cityCode                0
 cityName                0
 HotelCode               0
 HotelName               0
 HotelRating             0
 Address               102
 Attractions        525092
 Description         47005
 FaxNumber          560347
 HotelFacilities     50378
 Map                   930
 PhoneNumber        327137
 PinCode             30979
 HotelWebsiteUrl    250118
dtype: int64

In [ ]:
report = sv.analyze(df)
report.show_html('hotels_report_full.html')

                                             |          | [  0%]   00:00 -> (? left)

Report hotels_report_full.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
df.head(2)

,countyCode,countyName,cityCode,cityName,HotelCode,HotelName,HotelRating,Address,Attractions,Description,FaxNumber,HotelFacilities,Map,PhoneNumber,PinCode,HotelWebsiteUrl
0,AL,Albania,106078,Albanien,1003300,De Paris Hotel,FourStar,Nr. 7 Brigada Viii Street Tirane,NaN,Hotel de Paris is a charming boutique hotel th...,42268822,Private parking Parking onsite Television in c...,41.32213|19.81665,00355 4226 5009,1000,https://www.booking.com/hotel/al/de-paris.html
1,AL,Albania,106078,Albanien,1003301,Hotel Green,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,NaN,"Located in a suburb of Tirana, Hotel Green is ...",35548520058,airport pick up wifi available in all areas Ai...,41.30413|19.74703,+35548520057,1041,https://www.booking.com/hotel/al/hotel-green.html

In [ ]:
df.columns.tolist()

['countyCode',
 ' countyName',
 ' cityCode',
 ' cityName',
 ' HotelCode',
 ' HotelName',
 ' HotelRating',
 ' Address',
 ' Attractions',
 ' Description',
 ' FaxNumber',
 ' HotelFacilities',
 ' Map',
 ' PhoneNumber',
 ' PinCode',
 ' HotelWebsiteUrl']

In [ ]:
df_cleaned = df.rename(columns={
    ' countyName': 'countyName',
    ' cityName': 'cityName',
    ' HotelName': 'HotelName',
    ' HotelRating': 'HotelRating',
    ' Address': 'Address',
    ' Attractions': 'Attractions',
    ' Description': 'Description',
    ' HotelFacilities': 'HotelFacilities',
    ' PhoneNumber': 'PhoneNumber',
    ' PinCode': 'PinCode',
    ' HotelWebsiteUrl': 'HotelWebsiteUrl'
})

In [ ]:
df_cleaned=df_cleaned[['countyName', 'cityName', 'HotelName', 'HotelRating',
                 'Address', 'Description',
                 'HotelFacilities', 'PhoneNumber', 'PinCode']]

In [ ]:
df_cleaned

,countyName,cityName,HotelName,HotelRating,Address,Description,HotelFacilities,PhoneNumber,PinCode
0,Albania,Albanien,De Paris Hotel,FourStar,Nr. 7 Brigada Viii Street Tirane,Hotel de Paris is a charming boutique hotel th...,Private parking Parking onsite Television in c...,00355 4226 5009,1000
1,Albania,Albanien,Hotel Green,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,"Located in a suburb of Tirana, Hotel Green is ...",airport pick up wifi available in all areas Ai...,+35548520057,1041
2,Albania,Albanien,Theranda Hotel,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",face masks for guests available all plates cu...,00355 (0)42273766,1019
3,Albania,Albanien,Seven Hotel,ThreeStar,"KAVAJA STREET, CLOSE TURKISH AMBASSY TIRANA",This hotel enjoys an enviable setting in Tiran...,À la carte dinner Breakfast buffet Breakfast C...,NaN,1001
4,Albania,Albanien,Viktoria,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,Located in a new residential area at the edge ...,internet services Ironing service Family rooms...,355 69 5406986,1000
...,...,...,...,...,...,...,...,...,...
1010028,Zimbabwe,Victoria Falls,Eagles House,All,Aerodrome Suburbs,NaN,NaN,NaN,NaN
1010029,Zimbabwe,Victoria Falls,Losin Guest House,TwoStar,1271 Aerodrome Victoria Falls Town,<p>HeadLine : In a national park</p><p>Locatio...,Barbecue grill(s) Water dispenser Breakfast av...,263-783130516,00263
1010030,Zimbabwe,Victoria Falls,Victoria Falls Spacious Cottage,All,Syringa Road,"Featuring garden views, Victoria Falls Holiday...",Parking Private check-in/check-out Pets allowe...,NaN,NaN
1010031,Zimbabwe,Victoria Falls,848 Guest House,ThreeStar,848 Aerodrome,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Designated smokin...,263-772855945,263
1010032,Zimbabwe,Victoria Falls,Mbano Manor Hotel - All Inclusive,ThreeStar,Old Kazungula Road,<p>HeadLine : In a national park</p><p>Locatio...,Locally-owned & organized tours & activities F...,27-719012911,NaN

In [ ]:
df_cleaned.describe()

,countyName,cityName,HotelName,HotelRating,Address,Description,HotelFacilities,PhoneNumber,PinCode
count,1010033,1010033,1010033,1010033,1009931,963028,959655,682896,979054
unique,136,41821,719402,6,739796,732444,656894,433346,142146
top,United States,London,Quality Inn,ThreeStar,123 Main St,HotelDescription#Further information about thi...,Hotel,91-93-13931393,34747
freq,139868,5962,440,352613,637,687,12066,5505,3509

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010033 entries, 0 to 1010032
Data columns (total 9 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   countyName       1010033 non-null  object
 1   cityName         1010033 non-null  object
 2   HotelName        1010033 non-null  object
 3   HotelRating      1010033 non-null  object
 4   Address          1009931 non-null  object
 5   Description      963028 non-null   object
 6   HotelFacilities  959655 non-null   object
 7   PhoneNumber      682896 non-null   object
 8   PinCode          979054 non-null   object
dtypes: object(9)
memory usage: 69.4+ MB

In [ ]:
df_cleaned.dropna(inplace=True)

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651079 entries, 0 to 1010031
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   countyName       651079 non-null  object
 1   cityName         651079 non-null  object
 2   HotelName        651079 non-null  object
 3   HotelRating      651079 non-null  object
 4   Address          651079 non-null  object
 5   Description      651079 non-null  object
 6   HotelFacilities  651079 non-null  object
 7   PhoneNumber      651079 non-null  object
 8   PinCode          651079 non-null  object
dtypes: object(9)
memory usage: 49.7+ MB

In [ ]:
df_cleaned = df_cleaned.copy()
schema = pa.DataFrameSchema(
    {
        "countyName": Column(pa.String),
        "cityName": Column(pa.String),
        "HotelName": Column(pa.String),
        "HotelRating": Column(pa.String),
        "Address": Column(pa.String),
        "Description": Column(pa.String, nullable=True),
        "HotelFacilities": Column(pa.String, nullable=True),
        "PhoneNumber": Column(pa.String, nullable=True),
        "PinCode": Column(pa.String, nullable=True)
    },
)

C:\Users\menna\anaconda3\Lib\site-packages\pandera\_pandas_deprecated.py:143: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

In [ ]:
try:
    schema.validate(df_cleaned, lazy=True)
except pa.errors.SchemaErrors as exc:
    failure_cases_df = exc.failure_cases
    display(exc.failure_cases)

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651079 entries, 0 to 1010031
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   countyName       651079 non-null  object
 1   cityName         651079 non-null  object
 2   HotelName        651079 non-null  object
 3   HotelRating      651079 non-null  object
 4   Address          651079 non-null  object
 5   Description      651079 non-null  object
 6   HotelFacilities  651079 non-null  object
 7   PhoneNumber      651079 non-null  object
 8   PinCode          651079 non-null  object
dtypes: object(9)
memory usage: 49.7+ MB

In [ ]:
df_cleaned.to_csv("cleaned_hotels.csv",index=False)